<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ly</string>
	</array>
	<key>name</key>
	<string>Lightyear</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(\/\/).*$\n?</string>
			<key>name</key>
			<string>comment.line.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^[-a-zA-Z_][-\w]*)?(?=\()</string>
			<key>name</key>
			<string>meta.function.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.-?[_a-zA-Z]+[_a-zA-Z0-9-]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^ *&amp;amp;</string>
			<key>name</key>
			<string>entity.language.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(arguments)</string>
			<key>name</key>
			<string>variable.language.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$?\b([\$\w\-]+)(?=\s*[:\?]?=)</string>
			<key>name</key>
			<string>variable.assignment.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(\@[-\w]+)</string>
			<key>name</key>
			<string>keyword.at-rule.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\@)(?=[-\w])</string>
			<key>name</key>
			<string>variable.punctuation.property.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:+)\b(after|before|first-letter|first-line|selection)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-element.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:)\b(active|hover|focus|target|link|any-link|local-link|visited|scope|current|past|future|dir|lang|enabled|disabled|checked|indeterminate|default|valid|invalid|in-range|out-of-range|required|optional|read-only|read-write|root|first-child|last-child|only-child|nth-child|nth-last-child|first-of-type|last-of-type|nth-of-type|nth-last-of-type|only-of-type|nth-match|nth-last-match|empty|not|column|nth-column|nth-last-column)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-class.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(a|abbr|acronym|address|area|article|aside|audio|b|base|big|blockquote|body|br|button|canvas|caption|cite|code|col|colgroup|datalist|dd|del|details|dfn|dialog|div|dl|dt|em|eventsource|fieldset|figure|figcaption|footer|form|frame|frameset|(h[1-6])|head|header|hgroup|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|map|mark|menu|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|pre|progress|q|samp|script|section|select|small|span|strike|strong|style|sub|summary|sup|table|tbody|td|textarea|tfoot|th|thead|time|title|tr|tt|ul|var|video)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.tag.lightyear</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hex values.</string>
			<key>match</key>
			<string>(#)([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b</string>
			<key>name</key>
			<string>constant.other.color</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#)[a-zA-Z][a-zA-Z0-9_-]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.id.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-webkit-|-moz\-|-ms-|-o-)</string>
			<key>name</key>
			<string>meta.vendor-prefix.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|defined|null)\b</string>
			<key>name</key>
			<string>constant.language.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s)(!important|for|in|return|if|else|unless|return)\b</string>
			<key>name</key>
			<string>keyword.control.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?:\?|!|~|\+|-|(?:\*)?\*|\/|%|(?:\.)\.\.|&amp;lt;|&amp;gt;|(?:=|:|\?|\+|-|\*|\/|%|&amp;lt;|&amp;gt;)?=|!=)|\b(?:in|is(?:nt)?|not)\b)</string>
			<key>name</key>
			<string>keyword.operator.lightyear</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lightyear</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(gutter-width|outercol|innercol)\b(?=\:|\s\s*)</string>
			<key>name</key>
			<string>support.type.property-name.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*[a-zA-Z-]+\: </string>
			<key>name</key>
			<string>support.type.property-name.lightyear</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.unit.lightyear</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9]+)((?:px|pt|ch|cm|mm|in|r?em|ex|pc|deg|g?rad|dpi|dpcm|s)\b|%)?</string>
			<key>name</key>
			<string>constant.numeric.lightyear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[,:]</string>
			<key>name</key>
			<string>meta.delimiter.lightyear</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Root tags of form (tagname)</string>
			<key>match</key>
			<string>\([A-Za-z\.]+\)</string>
			<key>name</key>
			<string>entity.name.tag.lightyear</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lightyear</string>
	<key>uuid</key>
	<string>43fa6e40-8880-451c-b9f5-9f9f426225da</string>
</dict>
</plist>
